insert into public.catalog_media_type_definitions (
  key,
  owner_kind,
  display_name,
  usage_summary,
  bucket_name,
  max_upload_bytes,
  accepted_mime_types,
  aspect_width,
  aspect_height,
  allows_multiple,
  supports_video,
  recommended_width,
  recommended_height,
  accepted_file_types
)
values
  (
    'studio_avatar',
    'studio',
    'Studio avatar',
    'Used in compact studio identity spots, such as the square studio icon on studio cards and studio headers.',
    'avatars',
    262144,
    '["image/webp","image/jpeg","image/png"]'::jsonb,
    1,
    1,
    false,
    false,
    512,
    512,
    '["PNG","JPG","WEBP"]'::jsonb
  ),
  (
    'studio_logo',
    'studio',
    'Studio logo',
    'Used where the studio needs a horizontal brand mark or wordmark.',
    'logo-images',
    262144,
    '["image/webp","image/png","image/svg+xml"]'::jsonb,
    3,
    1,
    false,
    false,
    1200,
    400,
    '["PNG","WEBP","SVG"]'::jsonb
  ),
  (
    'studio_banner',
    'studio',
    'Studio banner',
    'Used as the wide studio header image at the top of studio surfaces.',
    'hero-images',
    3145728,
    '["image/webp","image/jpeg","image/png","image/svg+xml"]'::jsonb,
    21,
    9,
    false,
    false,
    1680,
    720,
    '["PNG","JPG","WEBP","SVG"]'::jsonb
  ),
  (
    'title_avatar',
    'title',
    'Title avatar',
    'Used in compact title identity spots, such as the small image beside the title name on cards and quick views.',
    'avatars',
    262144,
    '["image/webp","image/jpeg","image/png"]'::jsonb,
    1,
    1,
    false,
    false,
    512,
    512,
    '["PNG","JPG","WEBP"]'::jsonb
  ),
  (
    'title_card',
    'title',
    'Title card',
    'Used on browse tiles and other square title discovery cards.',
    'card-images',
    1572864,
    '["image/webp","image/jpeg","image/png"]'::jsonb,
    1,
    1,
    false,
    false,
    1200,
    1200,
    '["PNG","JPG","WEBP"]'::jsonb
  ),
  (
    'title_logo',
    'title',
    'Title logo',
    'Used for large horizontal title branding where a wordmark fits naturally.',
    'logo-images',
    262144,
    '["image/webp","image/png","image/svg+xml"]'::jsonb,
    3,
    1,
    false,
    false,
    1200,
    400,
    '["PNG","WEBP","SVG"]'::jsonb
  ),
  (
    'title_quick_view_banner',
    'title',
    'Title quick view banner',
    'Used in the wide thin image strip at the top of title quick view.',
    'hero-images',
    3145728,
    '["image/webp","image/jpeg","image/png","image/svg+xml"]'::jsonb,
    21,
    9,
    false,
    false,
    1680,
    720,
    '["PNG","JPG","WEBP","SVG"]'::jsonb
  ),
  (
    'title_showcase',
    'title',
    'Title showcase',
    'Used for title screenshots and videos in the full title gallery. The first item becomes the default title detail image.',
    'hero-images',
    3145728,
    '["image/webp","image/jpeg","image/png","image/svg+xml"]'::jsonb,
    16,
    9,
    true,
    true,
    1920,
    1080,
    '["PNG","JPG","WEBP","SVG"]'::jsonb
  )
on conflict (key) do update
set
  owner_kind = excluded.owner_kind,
  display_name = excluded.display_name,
  usage_summary = excluded.usage_summary,
  bucket_name = excluded.bucket_name,
  max_upload_bytes = excluded.max_upload_bytes,
  accepted_mime_types = excluded.accepted_mime_types,
  aspect_width = excluded.aspect_width,
  aspect_height = excluded.aspect_height,
  allows_multiple = excluded.allows_multiple,
  supports_video = excluded.supports_video,
  recommended_width = excluded.recommended_width,
  recommended_height = excluded.recommended_height,
  accepted_file_types = excluded.accepted_file_types,
  updated_at = now();

create or replace function public.reset_migration_demo_data()
returns void
language sql
security definer
as $$
  truncate table
    public.home_spotlight_entries,
    public.player_followed_studios,
    public.catalog_media_entries,
    public.title_showcase_media,
    public.title_metadata_version_genres,
    public.title_releases,
    public.title_metadata_versions,
    public.title_report_messages,
    public.title_reports,
    public.player_wishlist_titles,
    public.player_library_titles,
    public.title_media_assets,
    public.titles,
    public.studio_links,
    public.studio_memberships,
    public.studios,
    public.user_board_profiles,
    public.app_user_roles,
    public.app_users
  restart identity cascade;
$$;
